routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\PhrasesController;
use App\Http\Middleware\LanguageSwitcherMiddleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::middleware('switcher')->group(function () {
    Route::get('/', [PhrasesController::class, 'index'])->name('dashboard');

    Route::resource('phrases', PhrasesController::class);

    Auth::routes();
    Route::get('/home', [HomeController::class, 'index'])->name('home');
});


Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

app/Models/Phrase.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContracts;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Phrase extends Model implements TranslatableContracts
{
    use HasFactory;
    use Translatable;

    public $translatedAttributes = ['phrase'];
    protected $fillable = ['user_id'];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/PhraseTranslation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PhraseTranslation extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = ['phrase'];

}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function phrases(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Phrase::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LanguageSwitcherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LanguageSwitcherController extends Controller
{
    /**
     * @param Request $request
     * @param string $locale
     * @return \Illuminate\Http\RedirectResponse
     */
    public function switcher(Request $request, string $locale): \Illuminate\Http\RedirectResponse
    {
        $request->session()->put('locale', $locale);
        return back();
    }
}

app/Http/Controllers/PhrasesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Phrase;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PhrasesController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        $phrases = Phrase::orderBy('id', 'desc')->paginate(9);
        return view('phrases.index', compact('phrases'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $phrase = new Phrase();
        $data = [
            'en' => ['phrase' =>  $request->input('phrase'),],
                'ru' => ['phrase' => $request->input('phrase'),],
                'fr' => ['phrase' => $request->input('phrase'),],
                'ar' => ['phrase' => $request->input('phrase'),],
                'it' => ['phrase' => $request->input('phrase')],
            'user_id' => $request->user()->id
        ];

        $phrase->phrase = $request->input('phrase');
        $phrase->user_id = $request->user()->id;
        $phrase->save();

        return redirect(route('phrases.index'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Phrase $phrase): \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        return view('phrases.show', compact('phrase'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Phrase $phrase): \Illuminate\Routing\Redirector|\Illuminate\Contracts\Foundation\Application|RedirectResponse
    {
        $data = $request->validate([
            'en.phrase' => ['nullable'],
            'ru.phrase' => ['nullable'],
            'fr.phrase' => ['nullable'],
            'ar.phrase' => ['nullable'],
            'it.phrase' => ['nullable']
        ]);
        $phrase->update($data);
        return back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('phrases') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        <select class="custom-select" onchange="location = this.value;">
                            <option @if (session('locale') == 'en') selected @endif value="{{route('language.switcher', 'en')}}">
                                EN
                            </option>
                            <option @if (session('locale') == 'ru') selected @endif value="{{route('language.switcher', 'ru')}}">
                                RU
                            </option>
                        </select>
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                @yield('content')
            </div>
        </main>
    </div>
</body>
</html>

resources/views/phrases/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="col-12">
        <h1>{{__('Create new Phrase')}}</h1>
    </div>
    @if(auth()->check())
        <div class="col-12">
            <form method="post" action="{{route('phrases.store')}}">
                @csrf
                <div class="form-group">
                    <label for="phrase-title">{{__('Phrase')}}</label>
                    <input name="phrase" type="text" class="form-control"
                           id="phrase-title">
                </div>
                <button type="submit" class="btn btn-primary mt-3">{{__('Create phrase')}}</button>
            </form>
        </div>
    @endif

    <div class="row">
        @csrf
        @foreach($phrases as $phrase)
            <div class="col" style="padding: 35px 0 0 0;" id="delete-phrase-{{$phrase->id}}">
                <div class="card" style="width: 18rem;">
                    <div class="card-header">
                        {{ $phrase->phrase }}
                    </div>
                    <div class="card-body">
                        <a href="{{route('phrases.show', ['phrase' => $phrase])}}"
                           class="card-link">@lang('Show more') ...</a> <br>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    {{--    <div class="justify-content-md-center p-5">--}}
    {{--        <div class="col-md-auto">--}}
    {{--            {{ $phrase->links() }}--}}
    {{--        </div>--}}
    {{--    </div>--}}
@endsection

resources/views/phrases/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container text-center">
        <div class="row justify-content-center">
            <h1 class="text-danger">{{__('Translation of phrase')}}</h1>
            <h2 class="card-title">
                @if($phrase->translate('en'))
                    {{$phrase->translate('en')->phrase}}
                @else
                    <h5>Пока перевода нет</h5>
                @endif
            </h2>

        </div>
        <form action="{{route('phrases.update', ['phrase' => $phrase])}}" method="POST">
            @method('PUT')
            @csrf
            <div class="languages" style="display: block">
                <label for="ru" class="d-block my-3">
                    @lang('English')
                    <input type="text" name="en[phrase]"
                           @if($phrase->translate('en')) value="{{$phrase->translate('en')->phrase}}"  @endif
                           @if(!auth()->check()) disabled @endif>
                </label>
                <label for="ru" class="d-block my-3">
                    @lang('Russian')
                    <input type="text" name="ru[phrase]"
                           @if($phrase->translate('ru'))  value="{{$phrase->translate('ru')->phrase}}"  @endif
                           @if(!auth()->check()) disabled @endif>
                </label>
                <label for="ru" class="d-block my-3">
                    @lang('French')
                    <input type="text" name="fr[phrase]"
                           @if($phrase->translate('fr')) value="{{$phrase->translate('fr')->phrase}}"  @endif
                           @if(!auth()->check()) disabled @endif>
                </label>
                <label for="ru" class="d-block my-3">
                    @lang('Arabic')
                    <input type="text" name="ar[phrase]"
                           @if($phrase->translate('ar')) value="{{$phrase->translate('ar')->phrase}}"  @endif
                           @if(!auth()->check()) disabled @endif>
                </label>
                <label for="ru" class="d-block my-3">
                    @lang('Italian')
                    <input type="text" name="it[phrase]"
                           @if($phrase->translate('it')) value="{{$phrase->translate('it')->phrase}}"  @endif
                           @if(!auth()->check()) disabled @endif>
                </label>
            </div>
            @if(auth()->check())
                <button class="btn btn-outline-success mt-3">{{__('Submit')}}</button>
            @endif
        </form>
    </div>

@endsection